# Generated by Django 5.0.6 on 2024-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='validate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
