# Generated by Django 5.0.6 on 2024-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chronic_medfam_doctor_medanalyses_meddication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
