# Generated by Django 5.0.6 on 2024-06-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenets',
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='paied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment'),
        ),
    ]
