# Generated by Django 5.0.6 on 2024-06-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_paymenets_appointment_alter_appointment_paied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analiyses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medanalyses')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicalcert')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prescription')),
            ],
        ),
    ]
