# Generated by Django 5.0.6 on 2024-06-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chronic'),
        ),
    ]
