# Generated by Django 5.0.6 on 2024-06-03 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appointment_paied'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenets',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='paied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
